import "~@/styles/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "~@/components/themeprovider";
import Navbar from "~@/components/constants/navbar";
import Footer from "~@/components/constants/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { shadesOfPurple } from "@clerk/themes";
import { Toaster } from "sonner";
import RoleWrapper from "~@/components/role-guard";
// import RolePrompt from "~@/components/role-prompt";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  if (!process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY) return null;

  return (
    <ClerkProvider
      appearance={{
        baseTheme: shadesOfPurple,
      }}
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en" suppressHydrationWarning className="overflow-y-scroll">
        <body className={`${inter.className} px-4 overflow-none`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="md:hidden">
              <Toaster richColors position="top-center" />
            </div>

            <div className="hidden md:block">
              <Toaster richColors position="top-right" />
            </div>
            <RoleWrapper>
              <Navbar />
              <main className="min-h-screen">{children}</main>
              <Footer />
            </RoleWrapper>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
